### ISSUE TITLE
会支持QML吗

### ISSUE THREAD

**Issue by iamazy** [parallel101/qtguide#1]

**Comment by archibate** [comment]
【QML入门-与C++交互数据-哔哩哔哩】 https://b23.tv/BV1tx4y1t7Xy

感觉意义不明，没必要学qml，我既然想ml了为什么不html+css+js，前端框架，库，工具一抓一大把..会前端的程序员也一抓一大把

qml的东西是很不全的，比如zeno离不开的qgraphicsview，qopenglwidget就只有qtwidgets里有，qml啥也木有，基本只能画画方块形按钮啥也做不了，不知道是谁在炒作qml，严重高估了

qml属于脱离native api的直接gpu渲染，猜测qt的管理层提出qml是为了竞争浏览器，然而浏览器远比你成熟..我劝qt company少来东施效颦了，乖乖做好自己native客户端的生态位










无法顺畅的大口呼吸，是活着的最好证明

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月17日(周日) 下午5:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [parallel101/qtguide] 会支持QML吗 (Issue #1)

**Comment by iamazy** [comment]
有道理，那就学起来
