### ISSUE TITLE
Q_OBJECT

### ISSUE THREAD

**Issue by YH2021-cc** [parallel101/qtguide#3]
如果没看错的话为什么第二个示例没有使用Q_OBJECT宏但是都能正常使用信号和槽呢?

**Comment by archibate** [comment]
只有自定义了**信号**的类，才需要Q_OBJECT宏。
而我的案例中只用到了**槽**，我只是把QPushButton这个Qt内置类的信号连接到我自定义类的槽，所以我这个案例是不需要Q_OBJECT宏的。
而且如果要用Q_OBJECT，就必须分离头和源文件，否则Qt的MOC编译器会报错，例如MainWindow类必须分别定义在mainwindow.h和mainwindow.cpp。
而我的前两期课程为了方便讲解，全部的MainWindow和main函数都写在一个main.cpp里，如果加Q_OBJECT就报错了。
为了不增加新人学习的干扰项，所以故意避免使用自定义信号，并且不加Q_OBJECT宏。
下一期课程中会用到自定义信号，到时候会详细介绍Q_OBJECT宏与信号的实现原理。

注意哈，如果你用的是现代Qt的写法，**槽**已经不需要Q_OBJECT宏了，只有**信号**才需要。
但是古代Qt，**槽**和**信号**还是都需要Q_OBJECT宏的。
```cpp
connect(button, &QPushButton::clicked, this, &MainWindow::confirmButtonClicked); // 现代Qt（推荐）
connect(button, SIGNAL(clicked()), this, SLOT(confirmButtonClicked())); // 古代Qt
```
古代Qt的所谓SIGNAL和SLOT宏，实际上就是生成了字符串，运行时去查找字符串，而Q_OBJECT宏就是指示Qt的MOC编译器去生成函数名的字符串反射信息，只有`signals:`和`slots:`关键字后面的会被生成反射信息。
古代Qt的写法要求`confirmButtonClicked`这个槽函数定义在`public slots:`或`private:`后面，否则运行时报错。
现代Qt中，槽函数不再需要`slots:`才能使用，因为他已经不是使用字符串反射了，`confirmButtonClicked`这个槽函数定义在`public:`或`private:`后面一样可以正常使用。
并且由于现代Qt不用字符串动态反射查找函数，不仅运行效率更高，而且如果拼错了信号或槽函数名，编译期就能报错，而不是拖到运行时报错，提升开发效率。

**Comment by YH2021-cc** [comment]
明白了,谢谢解答
